name: statsbomb-explore
channels:
  - anaconda
dependencies:
  - jupyter
  - pandas
  - scipy
  - seaborn
  - beautifulsoup4
  - pyarrow
  - scikit-learn
  - pillow
  - openpyxl
  - pip
  - pip:
      - mplsoccer
